import { TableInfo } from '../connectors/types.js';
import { generateErDiagram } from './er-diagram.js';
import { generateTableDetails } from './table-details.js';

interface AssembleOptions {
  dbName: string;
  tables: TableInfo[];
  erDiagram: string;
  tableDetails: string;
  aiOverview?: string | null;
  aiFeatures?: string | null;
}

export function assembleMarkdown(opts: AssembleOptions): string {
  const date = new Date().toISOString().split('T')[0];
  const parts: string[] = [];

  parts.push(`# Database Schema: \`${opts.dbName}\``);
  parts.push(`> Generated by [db2md](https://github.com/your-org/db2md) on ${date}`);
  parts.push(`> **Tables:** ${opts.tables.length}  |  **Total rows:** ${totalRows(opts.tables)}`);

  parts.push('---');

  parts.push('## Project Overview');
  if (opts.aiOverview) {
    parts.push(opts.aiOverview);
  } else {
    parts.push('*AI analysis skipped. Set `AWS_ACCESS_KEY_ID` (or `AWS_PROFILE`) and re-run to generate a project overview.*');
  }

  parts.push('---');

  parts.push('## ER Diagram');
  parts.push(opts.erDiagram);

  parts.push('---');

  parts.push('## Tables');
  parts.push(opts.tableDetails);

  if (opts.aiFeatures) {
    parts.push('---');
    parts.push('## Possible Features');
    parts.push(opts.aiFeatures);
  }

  parts.push('---');
  parts.push('*Generated with [db2md](https://www.npmjs.com/package/db2md)*');

  return parts.join('\n\n');
}

function totalRows(tables: TableInfo[]): string {
  const total = tables.reduce((sum, t) => sum + (t.rowCount ?? 0), 0);
  return total.toLocaleString();
}
